<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MAP Home</title>
    <link rel="stylesheet" href="css/foundation.css" />
    <link rel="stylesheet" href="ise/map.css" />
    <script src="js/vendor/modernizr.js"></script>
    <script src="js/vendor/jquery.js"></script>
    <script src="ise/map.js"></script>
  </head>
  <body>
    <div class='fixed'>
      <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
          <li class="name">
            <h1 id="appname"><a href="index.php">M.A.P.</a></h1>
          </li>
           <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>
      
        <section class="top-bar-section">
          <!-- Right Nav Section 
          <ul class="right">
            <li class="active"><a href="#">Status</a></li>
            <li class="has-dropdown not-click">
              <a href="#">Right Button Dropdown</a>
              <ul class="dropdown">
                <li><a href="#">First link in dropdown</a></li>
                <li class="active"><a href="#">Active link in dropdown</a></li>
              </ul>
            </li>
          </ul>
          -->
          <!-- Left Nav Section -->
          <ul class="left">
            <li>
              <a id="history_btn" href="#">Event History</a>
            </li>
            <li><a id="task_btn" href="#">Task Status</a></li>
            <li><a id="template_btn" href="#">Templates</a></li>
          </ul>
        </section>
      </nav>

      <dl id="slidebar" class="sub-nav">
        <dd><a href="#">item 1</a></dd>
        <dd><a href="#">item 2</a></dd>
      </dl>
    </div><!--end of div fixed-->
    
    <div id='content'>
      <!--Everything within #content will be generated by php via ajax-->
      <div class='row'>
        <div class='small-10 small-centered columns'><!--Event History-->
          <div class='section_wrapper'>
            <div class='row'><!--start of header row-->
              <div id='section_header_10-0-040' class='small-12 columns section_header'>
                <div class='row'>
                  <div class='small-8 columns header_text'>
                    <h1 class='font_syncopate'>10.0.040</h1>
                  </div>
                  <div class='small-4 columns header_stat'>
                    <ul>
                      <li>BAT: Test Complete</li>
                      <li>OAT: Deploy Complete</li>
                      <li>PAT: Test Started</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div><!--end of header row-->
            <div class='row'><!--start of body row-->
              <div id='section_body_10-0-040' class='section_body'>
                <table>
                  <thead>
                    <tr>
                      <th>Template</th>
                      <th>Latest Event</th>
                      <th>Entry Time</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr class='event_history_template_row' data-ise-release='10.0.040' data-ise-template='oat' >
                      <td>OAT</td>
                      <td>Test Started</td>
                      <td>2014 15:00:23</td>
                    </tr>
                    <tr class='event_history_template_row' data-ise-release='10.0.040' data-ise-template='pat' >
                      <td>PAT</td>
                      <td>Deploy Completed</td>
                      <td>2014 15:00:23</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div><!--end of body row-->
          </div>
        </div><!--End of event history-->
        
        <hr>
          
        <!--Mockup for template instance-->
        <div class='row' data-equalizer>
          <!--OAT section-->
          <div class='small-6 columns end' data-equalizer-watch>
            <div class='template_header small-5 small-centered columns'>
              <h1 class='font_syncopate'>OAT</h1>
            </div>
            <div class='row'>
              <div class='small-12 small-centered columns'>
                <table>
                  <thead>
                    <tr>
                      <th width='50'>Instance</th>
                      <th width='50'>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><h3>OAT</h3></td>
                      <td class='btn_td'><a href='#' class='button tiny round suspend_btn'>Suspend</a></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div><!--End of OAT Section-->
          
          <!--OAT section-->
          <div class='small-6 columns end' data-equalizer-watch>
            <div class='template_header small-5 small-centered columns'>
              <h1 class='font_syncopate'>PAT</h1>
            </div>
            <div class='row'>
              <div class='small-12 small-centered columns'>
                <table>
                  <thead>
                    <tr>
                      <th width='50'>Instance</th>
                      <th width='50'>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><h3>PAT</h3></td>
                      <td class='btn_td'><a href='#' class='button tiny round suspend_btn'>Suspend</a></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div><!--End of PAT Section-->
          
          <!--OAT section-->
          <div class='small-6 columns end' data-equalizer-watch>
            <div class='template_header small-5 small-centered columns'>
              <h1  class='font_syncopate'>BAT</h1>
            </div>
            <div class='row'>
              <div class='small-12 small-centered columns'>
                <table>
                  <thead>
                    <tr>
                      <th width='50'>Instance</th>
                      <th width='50'>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><h3>BAT1</h3></td>
                      <td class='btn_td'><a href='#' class='button tiny round suspend_btn'>Suspend</a></td>
                    </tr>
                    <tr>
                      <td><h3>BAT2</h3></td>
                      <td class='btn_td'><a href='#' class='button tiny round suspend_btn'>Suspend</a></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div><!--End of BAT Section-->   
        </div><!--End of mockup for template instance-->
        <hr>
        
        <!--Mockup for Task Queue-->
        <div class='row' data-equalizer>
          <!--1Node section-->
          <div class='small-6 columns end' data-equalizer-watch>
            <div class='template_header small-8 small-centered columns'>
              <h1 class='font_syncopate'>1Node</h1>
            </div>
            <div class='row'>
              <div class='small-12 small-centered columns'>
                <table>
                  <thead>
                    <tr>
                      <th>Task ID</th>
                      <th width='70'>Release</th>
                      <th width='60'>Deploy</th>
                      <th>Test</th>
                      <th width='90'>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>20</td>
                      <td>010.000.030</td>
                      <td>Yes</td>
                      <td>Yes</td>
                      <td>In Progress</td>
                    </tr>
                    <tr>
                      <td>23</td>
                      <td>010.000.040</td>
                      <td>Yes</td>
                      <td>Yes</td>
                      <td>Pending</td>
                    </tr>
                    <tr>
                      <td>25</td>
                      <td>10.0.050</td>
                      <td>Yes</td>
                      <td>No</td>
                      <td>Pending</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div><!--End of 1Node Section-->
          
          <!--1Node section-->
          <div class='small-6 columns end' data-equalizer-watch>
            <div class='template_header small-5 small-centered columns'>
              <h1 class='font_syncopate'>OAT</h1>
            </div>
            <div class='row'>
              <div class='small-12 small-centered columns'>
                <table>
                  <thead>
                    <tr>
                      <th>Task ID</th>
                      <th width='70'>Release</th>
                      <th width='60'>Deploy</th>
                      <th>Test</th>
                      <th width='90'>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>20</td>
                      <td>010.000.030</td>
                      <td>Yes</td>
                      <td>Yes</td>
                      <td>In Progress</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div><!--End of OAT Section-->
          
          <!--PAT section-->
          <div class='small-6 columns end' data-equalizer-watch>
            <div class='template_header small-5 small-centered columns'>
              <h1 class='font_syncopate'>PAT</h1>
            </div>
            <div class='row'>
              <div class='small-12 small-centered columns'>
                <table>
                  <thead>
                    <tr>
                      <th>Task ID</th>
                      <th>Release</th>
                      <th>Deploy</th>
                      <th>Test</th>
                      <th>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>20</td>
                      <td>010.000.030</td>
                      <td>Yes</td>
                      <td>Yes</td>
                      <td>In Progress</td>
                    </tr>
                    <tr>
                      <td>23</td>
                      <td>010.000.040</td>
                      <td>Yes</td>
                      <td>Yes</td>
                      <td>Pending</td>
                    </tr>
                    <tr>
                      <td>25</td>
                      <td>10.0.050</td>
                      <td>Yes</td>
                      <td>No</td>
                      <td>Pending</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div><!--End of PAT Section-->
          
          <!--BAT section-->
          <div class='small-6 columns end' data-equalizer-watch>
            <div class='template_header small-5 small-centered columns'>
              <h1 class='font_syncopate'>BAT</h1>
            </div>
            <div class='row'>
              <div class='small-12 small-centered columns'>
                <table>
                  <thead>
                    <tr>
                      <th>Task ID</th>
                      <th width='70'>Release</th>
                      <th width='60'>Deploy</th>
                      <th>Test</th>
                      <th width='90'>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>20</td>
                      <td>010.000.030</td>
                      <td>Yes</td>
                      <td>Yes</td>
                      <td>In Progress</td>
                    </tr>
                    <tr>
                      <td>23</td>
                      <td>010.000.040</td>
                      <td>Yes</td>
                      <td>Yes</td>
                      <td>Suspended</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div><!--End of BAT Section-->
          
                    <!--BAT section-->
          <div class='small-6 columns end' data-equalizer-watch>
            <div class='template_header small-5 small-centered columns'>
              <h1 class='font_syncopate'>BAT</h1>
            </div>
            <div class='row'>
              <div class='small-12 small-centered columns'>
                <table>
                  <thead>
                    <tr>
                      <th>Task ID</th>
                      <th width='70'>Release</th>
                      <th width='60'>Deploy</th>
                      <th>Test</th>
                      <th width='90'>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>20</td>
                      <td>010.000.030</td>
                      <td>Yes</td>
                      <td>Yes</td>
                      <td>In Progress</td>
                    </tr>
                    <tr>
                      <td>23</td>
                      <td>010.000.040</td>
                      <td>Yes</td>
                      <td>Yes</td>
                      <td>Suspended</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div><!--End of BAT Section-->
          
                    <!--BAT section-->
          <div class='small-6 columns end' data-equalizer-watch>
            <div class='template_header small-5 small-centered columns'>
              <h1 class='font_syncopate'>BAT</h1>
            </div>
            <div class='row'>
              <div class='small-12 small-centered columns'>
                <table>
                  <thead>
                    <tr>
                      <th>Task ID</th>
                      <th width='70'>Release</th>
                      <th width='60'>Deploy</th>
                      <th>Test</th>
                      <th width='90'>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>20</td>
                      <td>010.000.030</td>
                      <td>Yes</td>
                      <td>Yes</td>
                      <td>In Progress</td>
                    </tr>
                    <tr>
                      <td>23</td>
                      <td>010.000.040</td>
                      <td>Yes</td>
                      <td>Yes</td>
                      <td>Suspended</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div><!--End of BAT Section-->
        </div><!--End of mockup for Task Queue-->
        <hr>
        <!--Mockup for Template-->
        <div class='row'>
          <div class='small-4 small-centered columns'>
            <table>
              <thead>
                <tr>
                  <th width='50'>Template</th>
                  <th width='50'>Action</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><h3>BAT</h3></td>
                  <td class='btn_td'><a href='#' class='button tiny round suspend_btn'>Suspend</a></td>
                </tr>
                <tr>
                  <td><h3>OAT</h3></td>
                  <td class='btn_td'><a href='#' class='button tiny round suspend_btn'>Suspend</a></td>
                </tr>
                <tr>
                  <td><h3>PAT</h3></td>
                  <td class='btn_td'><a href='#' class='button tiny round suspend_btn'>Suspend</a></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div><!--End of Mockup for Template-->
      </div>
    </div><!--End of content-->
   
   <!--Detailed Modal-->
  <div id="detail_modal" class="reveal-modal" data-reveal>
    <div class='row'>
      <div class='small-12 columns'>
        <h1 class='font_syncopate'>10.0.040 : OAT</h1>
      </div>
    </div>
    
    <div class='row'>
      <div class='modal_content small-12 columns'>
        <table>
          <thead>
            <tr>
              <th>Latest Event</th>
              <th>Entry Time</th>
            </tr>
          </thead>
          <tbody>
            <tr class='generic_table_row'>
              <td>Test Started</td>
              <td>2014 15:00:23</td>
            </tr>
            <tr class='generic_table_row'>
              <td>Deploy Completed</td>
              <td>2014 14:00:23</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <a class="close-reveal-modal">&#215;</a>
  </div>
    
   <!--End of Modal-->
    
    <!----------------- Foundation JS ------------------------------------->
    
    <script src="js/vendor/fastclick.js"></script>
    <script src="js/foundation.min.js"></script>
    <script>
      $(document).foundation();
    </script>
  </body>
</html>