<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );

# If PHP's memory limit is very low, some operations may fail.
# ini_set( 'memory_limit', '20M' );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename         = "AppSupportWiki";
$wgLocaltimezone = "America/New_York";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/ASWiki";
$wgScriptExtension  = ".php";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "hgu@ise.com";
$wgPasswordSender = "hgu@ise.com";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBname           = "wikidb";

$wgDBuser           = "root";
$wgDBpassword       = "";

#$wgDBuser           = "aswiki";
#$wgDBpassword       = "iseopt";

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = true;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = false;
# $wgUseImageMagick = true;
# $wgImageMagickConvertCommand = "/usr/bin/convert";

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
# $wgShellLocale = "en_US.UTF-8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

$wgLocalInterwiki   = strtolower( $wgSitename );

$wgLanguageCode = "en";

$wgSecretKey = "3817921b5e9b3b5395573ac6f634fc75928c5b23dba763c3bcff0234db49d56";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'monobook';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
# $wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

$wgDiff3 = "";

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$wgCacheEpoch = max( $wgCacheEpoch, gmdate( 'YmdHis', @filemtime( __FILE__ ) ) );

################################ISE#################################
#ISE Logo
$wgLogo = "{$wgScriptPath}/ise/ise.jpg"; 

# Disable anonymous editing 
#$wgWhitelistEdit = true; 
$wgGroupPermissions['*']['edit'] = false;

# Calendar
#include("$IP/extensions/SimpleCalendar.php");
#include_once("$IP/extensions/SemanticMediaWiki/includes/SMW_Settings.php");
#enableSemantics('172.24.106.236');
#require_once("$IP/extensions/SemanticResultFormats/SRF_Settings.php");
require_once("$IP/extensions/Calendar/Calendar.php");
// Puts events into their own namesspace/group (not included in 'main' searches... etc)
$wgExtraNamespaces[100] = "Calendars";
$wgExtraNamespaces[101] = "Precise_Calendars";
$wgExtraNamespaces[102] = "IORS_Calendars";
$wgExtraNamespaces[103] = "OMEX_Calendars";
$wgExtraNamespaces[104] = "CM_Calendars";
$wgExtraNamespaces[105] = "Midas_Calendars";
$wgExtraNamespaces[106] = "Sur_Calendars";
$wgExtraNamespaces[107] = "HOT.data_Calendars";
//Note: 'Calendars' is an example, please feel free to use whatever name you wish

// Puts the events into Subpages (allows a quick link back to primary calendar)
$wgNamespacesWithSubpages[100] = true;
$wgNamespacesWithSubpages[101] = true;
$wgNamespacesWithSubpages[102] = true;
$wgNamespacesWithSubpages[103] = true;
$wgNamespacesWithSubpages[104] = true;
$wgNamespacesWithSubpages[105] = true;
$wgNamespacesWithSubpages[106] = true;
$wgNamespacesWithSubpages[107] = true;

# FCKeditor
#require_once("$IP/extensions/CKeditor/CKeditor.php");
require_once("$IP/extensions/fckeditor/fckeditor.php");
$wgUseAjax = 'true';

# For Tabber
require_once("$IP/extensions/tabber/tabber.php");

# Skin
$wgDefaultSkin = 'cavendish';

# Enable File Upload
$wgEnableUploads = true; # Enable uploads
$wgFileExtensions = array('png', 'gif', 'jpg', 'jpeg', 'doc', 'xls', 'mpp', 'pdf', 'zip', 'docx', 'xlsx', 'ppt');

$wgStrictFileExtensions = false; # allow most of the files to be uploaded

# SimpleTable Extension
require_once("$IP/extensions/SimpleTable.php");

# Task List
include("extensions/Tasks.php");
include("includes/SpecialTasks.php");

# Issue Tracker
require_once $IP . '/extensions/IssueTracker/IssueTracker.php';

# User Merge and Delete
require_once( "$IP/extensions/UserMerge/UserMerge.php" );
$wgGroupPermissions['bureaucrat']['usermerge'] = true;

# Prevent new user registrations except by sysops
$wgGroupPermissions['*']['createaccount'] = false;

# Password Protection for pages
#require_once("$IP/extensions/passwordpages.php");

# Event CountDown
require_once("extensions/EventCountdown.php");

# Tree and Menu
#include("$IP/extensions/TreeAndMenu/TreeAndMenu.php");




